name: HealAfterSleep
main: com.Mo0od.healaftersleep.HealAfterSleep
version: 0.0.4
author: Mo0od
api-version: 1.17
commands:
  HealAfterSleep:
    description: HealAfterSleep help menu
    usage: /<command>

  HealAfterSleep reload:
    description: HealAfterSleep reload config
    usage: /<command>
    permission: HAS.reload
